### ISSUE TITLE
Deobfuscator

### ISSUE THREAD

**Issue by therealOri** [billythegoat356/Hyperion#12]
Found a Hyperion Deobfuscator. (I think)

https://github.com/Bleu-No/Hyperion-Deobfuscate

No idea if it actually works xD
But, I guess this means...time for more layers and stuff.

**Comment by therealOri** [comment]
(This is more of a notice than an "issue" and maybe the readme will be updated)

**Comment by billythegoat356** [comment]
Yep i'm adding one more protection rn!

**Comment by billythegoat356** [comment]
And anyways it's not a problem if there is a deobfuscator ;) it's cool

**Comment by therealOri** [comment]
Noice.

And like I said, this was meant as a notice for you to update your readme and to bring some attention to it (the deobfuscator)
