### ISSUE TITLE
Le webhook ne reçois plus d'info après passage en EXE

### ISSUE THREAD

**Issue by nolan70gaming** [billythegoat356/Hyperion#24]
Après obfuscation tout va bien je reçois les info nécessaires sur mon webhook, mais après le passage en .exe je ne reçois plus rien sur mon webhook.
Aucun code d'erreur à fournir, j'ai utiliser pyinstaller comme suggéré avec une autre personne j'ai bien mon .exe mais qui ne sert plus à rien

**Comment by CSM-BlueRed** [comment]
c pas toi le mec que j'ai croisé a montigny c moi isaac meme on ct posé la avc d potes
![image](https://github.com/billythegoat356/Hyperion/assets/89811976/0783eafb-7f82-4fd8-840d-62e9a32a04a4)

**Comment by nolan70gaming** [comment]
Oula non

**Comment by CSM-BlueRed** [comment]
ah ok dsl
